CSHARP-2905: Make ExceededTimeLimit retryable writes error.
DmitryLukyanov/mongo-csharp-driver pull request #106
Opened 2020-02-07 12:44 UTC by DmitryLukyanov

EG: https://evergreen.mongodb.com/version/5e3d5a20d6d80a566eee1cbb

2020-02-13 23:34 UTC, DmitryLukyanov commented on src/MongoDB.Driver/TransactionExecutor.cs
> +        private const int MaxTimeMSExpiredErrorCode = 50;
I've checked it in this spec: https://github.com/mongodb/specifications/commit/8a2c678ff8fe9144870cec835554181dd6639fa3#diff-1c9bb9c2c4a17174d2c5d541152dd96bR274
It was named `MaxTimeMSExpired` originally, it looks like the only reason why we named it `ExceededTimeLimitErrorCode` is because we had such code mapping in ServerErroCode.cs

2020-02-13 23:34 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/RetryabilityHelper.cs
> +                        case ServerErrorCode.ExceededTimeLimit:
We don't have such a case in the provided tests, however, I think there is no harm to add `ExceededTimeLimit` condition here too. At the very least. this switch contains some other codes from documentation for example `ShutdownInProgress`: https://github.com/mongodb/specifications/commit/d05e8843b317789d631ed2b4563126e15ce64c80#diff-8aaf18b3cf5d8b4260afb96c1517114aR251

2020-02-13 23:36 UTC, DmitryLukyanov commented
ready for review

2020-02-14 18:40 UTC, rstam requested changes
A few minor comments. Almost LGTM.

2020-02-14 18:40 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Operations/RetryabilityHelper.cs
> +                        case ServerErrorCode.ExceededTimeLimit:
Is `ExceededTimeLimit` in fact retryable?

2020-02-14 18:40 UTC, rstam commented on src/MongoDB.Driver.Core/ServerErrorCode.cs
> +        MaxTimeMSExpired= 50
Add space before `=`.

2020-02-14 18:40 UTC, rstam commented on src/MongoDB.Driver.Core/ServerErrorCode.cs
> +        MaxTimeMSExpired= 50
It's fine to add this value to the enum, but I don't see it actually used anywhere.

2020-02-14 18:40 UTC, rstam commented on src/MongoDB.Driver/TransactionExecutor.cs
> +        private const int MaxTimeMSExpiredErrorCode = 50;
The renaming is fine.

2020-02-14 20:30 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/ServerErrorCode.cs
> +        MaxTimeMSExpired= 50
done

2020-02-14 20:30 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/ServerErrorCode.cs
> +        // see: https://github.com/mongodb/mongo/blob/master/src/mongo/base/error_codes.yml
the previous address is not available anymore

2020-02-14 20:30 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Operations/RetryabilityHelper.cs
> +                        case ServerErrorCode.ExceededTimeLimit:
discussed offline

2020-02-21 15:38 UTC, MikalaiMazurenka approved these changes
LGTM!

2020-02-27 19:13 UTC, rstam approved these changes
LGTM

2020-03-02 13:55 UTC, closed without merging