CSHARP-3061: Clarify how a driver must handle wrong set name in single topology.
DmitryLukyanov/mongo-csharp-driver pull request #133
Opened 2020-04-24 23:21 UTC by DmitryLukyanov

2020-04-27 23:54 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Tests/MongoClientSettingsTests.cs
> -        [InlineData("mongodb+srv://username:password@test5.test.build.10gen.cc/?connect=direct", ConnectionStringScheme.MongoDB, "localhost.test.build.10gen.cc:27017")]
This test fails with the new requirement regarding directConnection. They're described here:https://github.com/mongodb/specifications/commit/e56f5eceed7729f8b9b43a4a1f76c7e5840db49f#diff-5e688c46cf9e7c28e7b4b821cf4cd145R66

2020-04-28 15:47 UTC, rstam requested changes
In general looks good. Some minor changes requested.

2020-04-28 15:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/SingleServerCluster.cs
> +            if (_replicaSetName != null && newServerDescription.ReplicaSetConfig != null)
What if `_replicaSetName` is not null but `newServerDescription.ReplicaSetConfig` IS null?

Shouldn't we set the `ServerType` to `Unknown` in that case also?

2020-04-28 15:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Clusters/SingleServerCluster.cs
> +            if (_replicaSetName != null && newServerDescription.ReplicaSetConfig != null)
I propose we refactor this new code as:

    if (_replicaSetName != null)
    {
        var replicaSetConfig = newServerDescription.ReplicaSetConfig;
        if (replicaSetConfig == null || replicaSetConfig.Name != _replicaSetName)
        {
            // if the replica set name does not match then the ServerType in the ServerDescription MUST be replaced with Unknown
            newServerDescription = newServerDescription.With(type: ServerType.Unknown);
        }
    }

Note: the comment has been updated also

2020-04-28 15:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                throw new MongoConfigurationException("Specifying both connect and directConnection is invalid.");
Suggested error message change:

    throw new MongoConfigurationException("Connect and directConnection cannot both be specified.");

2020-04-28 15:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                throw new MongoConfigurationException("Direct connect is not allowed to be used with SRV.");
Suggested error message change:

     throw new MongoConfigurationException("Direct connect cannot be used with SRV.");

2020-04-28 15:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                throw new MongoConfigurationException("Direct connect is not allowed to be used with multiple seeds.");
Suggested error message change:

    throw new MongoConfigurationException("Direct connect cannot be used with multiple host names.");

2020-04-28 15:47 UTC, rstam commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +        private ClusterConnectionMode? GetEffectiveConnectionMode(ClusterConnectionMode? mode, bool? directConnection, string replicaSet)
Change `mode` parameter name to `connect` (to match the _connect field it corresponds to).

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/SingleServerClusterTests.cs
> +        public void ServerDescription_type_should_be_replaced_on_Unknown_when_isMaster_setName_wrong(
Rename method to:

    ServerDescription_type_should_be_replaced_with_Unknown_when_isMaster_setName_is_different

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            result.Should().Be(directConnection);
Change assertions to:

    subject.Connect.Should().Be(connect);
    subject._directConnection().Should().Be(directConnection);

Note: requires adding a `ConnectionStringReflector` class (unless you add a `DirectConnection` public property).

    public static class ConnectionStringReflector
    {
        public static bool _directConnection(this ConnectionString obj) => (bool)Reflector.GetFieldValue(obj, nameof(_directConnection));
    }

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            ConnectionString result = null;
Rename `result` to `subject`.

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +                directConnection.Should().BeFalse();
Change assertions to:

    exception.Should().BeNull();
    subject._directConnection().Should().BeFalse();

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            ConnectionString result = null;
Rename `result` to `subject`.

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +                directConnection.Should().BeFalse();
Replace assertions with:

    exception.Should().BeNull();
    subject._directConnection().Should().BeFalse();

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        public void When_a_directConenction_is_specified(string connectionString, bool directConnection, ClusterConnectionMode mode)
Rename `mode` parameter to `connect`.

2020-04-28 15:47 UTC, rstam commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        public void When_a_directConnection_is_specified_with_multiple_seeds(string connectionString, bool shouldThrow)
Rename method to:

    When_a_directConnection_is_specified_with_multiple_hosts

"seeds" only applies to replica sets. Multiple hosts is more generic (e.g. it applies to shard routers also).

2020-04-28 16:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                throw new MongoConfigurationException("Specifying both connect and directConnection is invalid.");
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                throw new MongoConfigurationException("Direct connect is not allowed to be used with SRV.");
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +                throw new MongoConfigurationException("Direct connect is not allowed to be used with multiple seeds.");
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Configuration/ConnectionString.cs
> +        private ClusterConnectionMode? GetEffectiveConnectionMode(ClusterConnectionMode? mode, bool? directConnection, string replicaSet)
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Clusters/SingleServerClusterTests.cs
> +        public void ServerDescription_type_should_be_replaced_on_Unknown_when_isMaster_setName_wrong(
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            result.Should().Be(directConnection);
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            ConnectionString result = null;
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        public void When_a_directConnection_is_specified_with_multiple_seeds(string connectionString, bool shouldThrow)
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +            ConnectionString result = null;
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +                directConnection.Should().BeFalse();
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.Core.Tests/Core/Configuration/ConnectionStringTests.cs
> +        public void When_a_directConenction_is_specified(string connectionString, bool directConnection, ClusterConnectionMode mode)
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/SingleServerCluster.cs
> +            if (_replicaSetName != null && newServerDescription.ReplicaSetConfig != null)
done

2020-04-28 16:42 UTC, DmitryLukyanov commented on src/MongoDB.Driver.Core/Core/Clusters/SingleServerCluster.cs
> +            if (_replicaSetName != null && newServerDescription.ReplicaSetConfig != null)
it took time to understand that ReplicaSetConfig is presented only in the driver side

2020-04-28 16:44 UTC, DmitryLukyanov commented
EG: https://evergreen.mongodb.com/version/5ea85d4d9ccd4e57ae2259eb
ready for review

2020-04-28 17:06 UTC, rstam approved these changes
LGTM

2020-04-29 20:56 UTC, jyemin approved these changes
LGTM

2020-05-06 12:21 UTC, closed without merging