CSHARP-2629: Remove workaround.
DmitryLukyanov/mongo-csharp-driver pull request #69
Opened 2019-10-25 12:05 UTC by DmitryLukyanov

evergreen: https://evergreen.mongodb.com/version/5db2e4a530661572d3e8af05

2019-10-31 15:28 UTC, DmitryLukyanov commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
> +            if (CoreTestConfiguration.Cluster.Description.Type != ClusterType.Sharded)
According to spec, this option makes sense only for sharded topologies

2019-10-31 16:06 UTC, rstam commented
The timestamps on the commit are wrong. It "looks" like this PR has been pending for 6 days but it only just today showed up in my github,com/pulls queue.

2019-10-31 16:09 UTC, DmitryLukyanov commented
> 
> 
> The timestamps on the commit are wrong. It "looks" like this PR has been pending for 6 days but it only just today showed up in my github,com/pulls queue.

yep, I created a draft PR to track evergreen patches which I've created for this ticket. Then I converted this PR to the usual PR

2019-10-31 16:11 UTC, rstam commented
> yep, I created a draft PR to track evergreen patches which I've created for this ticket. Then I converted this PR to the usual PR

But the commit itself is dated 6 days ago, and I'm pretty sure you made changes this morning.

2019-10-31 16:19 UTC, DmitryLukyanov commented
> 
> 
> > yep, I created a draft PR to track evergreen patches which I've created for this ticket. Then I converted this PR to the usual PR
> 
> But the commit itself is dated 6 days ago, and I'm pretty sure you made changes this morning.

yep, squashing issue :)

2019-11-01 16:00 UTC, rstam approved these changes
LGTM

2019-11-04 21:35 UTC, rstam requested changes
I'm reverting my LGTM because it is no longer clear to me that the original workaround or the changes in this pull request have anything to do with SERVER-41532.

2019-11-04 22:51 UTC, rstam commented
We have determined that the workaround mentioned in CSHARP-2629 was actually a workaround for SERVER-40685 and not SERVER-41532.

The JIRA ticket has been updated accordingly.

2019-11-04 22:53 UTC, rstam approved these changes
Now that we have corrected the JIRA ticket to indicate that the workaround we are removing was actually for SERVER-40685 (which is fixed) and not SERVER-41532 (which is not fixed) I can LGTM this pull request again.

2019-11-06 16:07 UTC, vincentkam approved these changes
Glad to see the workaround go! LGTM! 😸

2019-11-06 16:07 UTC, vincentkam commented on tests/MongoDB.Driver.TestHelpers/DriverTestConfiguration.cs
>              bool useMultipleShardRouters = false)
Just noting that most of our test runners call this function with the default value of false for `useMultipleShardRouters`. If I recall correctly, when we discussed this some time ago, we were okay with only testing against multiple shard routers only when the tests specifically called for them. (Confirmed with @jyemin offline).

2019-11-06 16:33 UTC, closed without merging